# Generated by Django 3.1.2 on 2020-12-07 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Fold',
        ),
    ]
