# Generated by Django 3.1.2 on 2020-12-07 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_delete_fold'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='stdin',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='folder',
            name='language',
            field=models.CharField(choices=[('Python', 'Python'), ('C++', 'C++'), ('Java', 'Java'), ('Bash', 'Bash')], default='c++', max_length=10),
        ),
    ]
