# Generated by Django 3.1.2 on 2020-12-07 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20201207_0632'),
    ]

    operations = [
        migrations.CreateModel(
            name='Code',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.TextField()),
                ('language', models.CharField(choices=[('Python', 'Python'), ('C++', 'C++'), ('Java', 'Java'), ('Bash', 'Bash')], max_length=10)),
                ('CLI', models.BooleanField(default=False)),
                ('CLI_args', models.TextField(blank=True)),
                ('stdin', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'codes',
            },
        ),
    ]
