# Generated by Django 3.1.2 on 2020-12-07 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_code'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='code',
            options={},
        ),
    ]
